Sp2 e2 miso 83
MISO4101-202010/Proyecto-Frontend pull request #30
Opened 2020-04-27 02:02 UTC by MateoLeon44

2020-04-27 15:19 UTC, mateodevia commented on src/app/contenido-interactivo/configurar-contenido-interactivo/configurar-contenido-interactivo.component.ts
> +      this.setPreguntaToMark(selectedMark);
La llamada a las son asincrónicas por lo tanto cuando hay varias marcas configuradas (del order de 15 marcas) en un contenido el llamado se demora. Esto esta causando un bug porque cuando hay varias y uno le hace doble click para editar hay ocasiones en las que no alcanza a cargar entonces el doble click no funciona y no abre la ventana de editar.

2020-04-27 15:22 UTC, mateodevia requested changes

2020-04-27 15:22 UTC, mateodevia commented on src/app/contenido-interactivo/configurar-contenido-interactivo/configurar-contenido-interactivo.component.ts
> +      this.setPreguntaToMark(selectedMark);
La llamada a las son asincrónicas por lo tanto cuando hay varias marcas configuradas (del order de 15 marcas) en un contenido el llamado se demora. Esto esta causando un bug porque cuando hay varias y uno le hace doble click para editar hay ocasiones en las que no alcanza a cargar entonces el doble click no funciona y no abre la ventana de editar. ¿podrían establecer algún mecanismo de sincronización para que esto no ocurra?

2020-04-28 03:22 UTC, juanalvarez123 commented on src/app/contenido-interactivo/configurar-contenido-interactivo/configurar-contenido-interactivo.component.ts
> +      this.setPreguntaToMark(selectedMark);
Hola Mateo. Sí había un bug en la aplicación y gracias por notarlo. Pero en realidad no estaba relacionado con el tiempo/demora en el llamado del end-point.

La verdadera razón era por que un end-point de las marcas estaba devolviendo solo los 10 primeros registros de las marcas, y yo estaba esperando todas las marcas del video. Esto estaba causando que al darle doble click a la marca #11, #12, #13, etc ... saliera un error. Envié este PR en el backend para solucionarlo: https://github.com/MISO4101-202010/Proyecto-Backend/pull/23/files

Las pruebas en el frontend las hice con un video con aproximadamente 20+ marcas y todo funcionó bien:
![image](https://user-images.githubusercontent.com/8230172/80443511-03b7a500-88d5-11ea-87ea-b79edc7b4871.png)

2020-04-28 21:43 UTC, juanalvarez123 commented on src/app/contenido-interactivo/configurar-contenido-interactivo/configurar-contenido-interactivo.component.ts
> +        this.marcas = val;
En `video-alumno.component.ts` hay otro llamado similar, me imagino que también hay que hacer ese ajuste allá

2020-04-28 21:45 UTC, larry852 commented on src/app/contenido-interactivo/configurar-contenido-interactivo/configurar-contenido-interactivo.component.ts
> +        this.marcas = val;
Efectivamente, cambio realizado.

2020-04-28 21:59 UTC, larry852 approved these changes

2020-04-28 21:59 UTC, juanalvarez123 approved these changes
👍

2020-04-28 21:59 UTC, merged